### ISSUE TITLE
can't shutdown provisioned wildfly server

### ISSUE THREAD

**Issue by liweinan** [liweinan/resteasy-wildfly#5]

**Comment by liweinan** [comment]
@jamezp I have configured `wildfly-maven-plugin` to shutdown the provisioned wildfly server:

- https://github.com/liweinan/resteasy-wildfly/blob/main/pom.xml#L123

However if I run the command:

```bash
$ mvn integration-test
```

After the tests passed, the server won't shutdown and block there:

<img width="1367" alt="image" src="https://github.com/liweinan/resteasy-wildfly/assets/201907/7f93e9b5-565e-48b5-ad0d-a1bde89cc2bc">

But if I run:

```bash
$ mvn verify
```

The server can shutdown correctly:

<img width="1735" alt="image" src="https://github.com/liweinan/resteasy-wildfly/assets/201907/96ac1c29-586d-4677-9437-fb8b72bb470c">

Is there anything I configure incorrectly?

In addition, is there anyway I can configure `wildfly-maven-plugin` to shutdown server unconditionally?

**Comment by jamezp** [comment]
When you run the `integration-test` phase, it doesn't execute the `post-integration-test` phase which is why it's not shutting down. Have a look at the default lifecycles https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#default-lifecycle.

**Comment by liweinan** [comment]
@jamezp Thanks for teaching James!

In addition, if here are test failures, even if I run `mvn verify`, it seems the whole process will get stuck in the `integrate-test` phase and the wildfly server will stay running and won't get shutdown.

Is there anyway that the wildfly server can be shutdown unconditionally no matter there are test failures or not?

**Comment by liweinan** [comment]
@jamezp Thanks for teaching! Maybe I met some other problems. I'll try to investigate on this.
